# UPM Package Deployment
# Author:   AndrewMJordan
# Version:  1.0.3

name: $(BuildID)

trigger:
  - master
pr: none

pool:
  vmImage: 'windows-latest'
  
stages:
- stage: deploy
  displayName: "Deployment Stage"
  jobs:
  - job: deploy1
    displayName: "Publish UPM Package Contents"
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        dotnet tool install --global Gooball
      displayName: 'Install Unity CLI'
    - bash: |
        git config user.name "Azure Pipelines"
        git config user.email "<>"
      displayName: 'Configure version control'
    - bash: |
        cd "$(Build.SourcesDirectory)"

        find "$(Custom.PackageRoot)" \( -iname "*.cs" -o -iname "*.shader" \) | while read fname; do
          cat "preamble.txt" | goo transform inject "${fname}"
        done

        goo transform hide-folder "$(Custom.PackageRoot)/Samples"
        goo package ignore-folder "$(Custom.PackageRoot)" "Samples"
      displayName: 'Preprocess package files'
    - bash: |
        cd $"(Build.SourcesDirectory)"

        temp="$(Agent.TempDirectory)/package"
        cp -r "$(Custom.PackageRoot)"/. "${temp}"/

        git checkout -fb upm && git clean -df
        git rm -r *
        mv "${temp}"/* .

        version=`goo package get-version .`

        git add -A
        git commit -m "Deployed ${version} by Azure Pipelines"
        git tag -a -m "Release tag by Azure Pipelines" "${version}"

        git push -f origin upm && git push origin --tags
      displayName: 'Push with package structure'
