# UPM Package Deployment
# Author:   AndrewMJordan
# Version:  1.0.0

name: $(BuildID)

trigger:
  - master
pr: none

pool:
  vmImage: 'windows-latest'
  
stages:
- stage: deploy
  displayName: "Deployment Stage"
  jobs:
  - job: deploy1
    displayName: "Publish UPM Package Contents"
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        dotnet tool install --global Gooball
      displayName: 'Install Unity CLI'
    - bash: |
        git config user.name "Azure Pipelines"
        git config user.email "<>"
      displayName: 'Configure version control'
    - bash: |
        cd "$(Build.SourcesDirectory)"

        find "$(Custom.PackageRoot)" \( -iname "*.cs" -o -iname "*.shader" \) | while read fname; do
          cat "preamble.txt" | goo transform inject "${fname}"
        done

        goo transform hide-folder "$(Custom.PackageRoot)/Samples"
        goo package ignore-folder "$(Custom.PackageRoot)" "Samples"
      displayName: 'Preprocess files'
    - bash: |
        temp="$(Agent.TempDirectory)/package"
        cp -r "$(Custom.PackageRoot)"/. "${temp}"/

        git checkout -f upm && git clean -df
        git rm -r *
        mv "${temp}"/* "$(Build.SourcesDirectory)"
      displayName: 'Prepare package file structure'
    - bash: |
        git add -A
        git commit -m "[skip cip] Deployed by Azure Pipelines"

        git push -f origin upm
      displayName: 'Push package branch'
