name: $(BuildID)

variables:
  projectPath: "$(Agent.BuildDirectory)/$(Custom.ProjectRoot)"
  packagePath: "$(Agent.BuildDirectory)/$(Custom.PackageRoot)"
  licenseHeader: "$(Custom.LicenseText)"

trigger:
  - master
pr: none
  
stages:
- stage: deploy
  displayName: "Deployment Stage"
  jobs:
  - job: deploy.1
    displayName: "Publish UPM Package Contents"
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global Gooball'
      displayName: 'Install Unity CLI tool'
    - bash: |
        find . -type f -name "$(packagePath)/*.cs" | xargs -I {} sh -c "echo '$(licenseHeader)' | goo transform inject {}"
        find . -type f -name "$(packagePath)/*.shader" | xargs -I {} sh -c "echo '$(licenseHeader)' | goo transform inject {}"
        goo transform hide-folder "$(packagePath)/Samples"
        goo package ignore-folder "$(packagePath)" "Samples"
      displayName: 'Preprocess files'
    - bash: |
        git subtree split -P "$(packagePath)" -b upm
        git push origin upm

        ver=`goo package get-version '$(packagePath)'
        git tag upm -a "Release tag by Azure Pipelines" -m "$ver"
      displayName: 'Push package branch'
